// MapLibre paints from literals, never CSS variables: keep these in step with `main.css`.

import type { Map } from 'maplibre-gl'

/** Free vector tiles, no API key and no quota. OpenStreetMap data, OpenMapTiles schema. */
export const MAP_STYLE = 'https://tiles.openfreemap.org/styles/positron'

/** The upstream style shows `name:latin` — "Brittany", "Upper France" on a French map. */
export const FRENCH_LABELS = ['coalesce', ['get', 'name:fr'], ['get', 'name:latin'], ['get', 'name']]

/** Generated by `scripts/build-rail-network.py`. */
export const RAIL_NETWORK = '/rail-network.geojson'

const TINTS: Array<{ id: string, prop: string, color: string }> = [
  { id: 'background', prop: 'background-color', color: '#faf9f5' },
  { id: 'water', prop: 'fill-color', color: '#d8e7ea' },
  { id: 'park', prop: 'fill-color', color: '#e9ece3' },
  { id: 'landcover_wood', prop: 'fill-color', color: '#e4e9e0' },
  { id: 'landuse_residential', prop: 'fill-color', color: '#f3f1ec' },
]

export function styleBaseMap(map: Map) {
  for (const layer of map.getStyle().layers ?? []) {
    if (layer.type !== 'symbol') continue
    const textField = layer.layout?.['text-field']
    // Name layers only: road shields use `ref` and would be blanked by the substitution.
    if (!textField || !JSON.stringify(textField).includes('name')) continue
    try {
      map.setLayoutProperty(layer.id, 'text-field', FRENCH_LABELS)
    } catch {
      // An upstream layer changed shape: keep its original label.
    }
  }

  for (const { id, prop, color } of TINTS) {
    if (!map.getLayer(id)) continue
    try {
      map.setPaintProperty(id, prop, color)
    } catch {
      // Same: the tint is cosmetic, failing to apply it must not break the map.
    }
  }
}
