# Generated by Django 6.0.7 on 2026-08-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("train_no", models.CharField(max_length=8)),
                ("origin", models.CharField(max_length=64)),
                ("destination", models.CharField(max_length=64)),
                ("departure", models.TimeField()),
                ("arrival", models.TimeField()),
                ("bookable", models.BooleanField(default=True)),
                ("first_seen", models.DateField()),
                ("last_seen", models.DateField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["origin", "date", "bookable"], name="offer_from_idx"),
                    models.Index(fields=["destination", "date", "bookable"], name="offer_to_idx"),
                    models.Index(fields=["date", "bookable"], name="offer_day_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "date",
                            "train_no",
                            "origin",
                            "destination",
                            "departure",
                            "arrival",
                        ),
                        name="offer_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seen_on", models.DateField()),
                ("bookable", models.BooleanField()),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="tgvmax.offer",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["seen_on"], name="change_day_idx")],
            },
        ),
    ]
