# Generated by Django 6.0.7 on 2026-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgvmax", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=64, unique=True)),
                ("first_seen", models.DateField()),
                ("last_seen", models.DateField()),
            ],
        ),
    ]
