# Generated by Django 6.0.7 on 2026-08-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgvmax", "0002_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("axis", models.CharField(max_length=32)),
                ("total", models.PositiveIntegerField()),
                ("eligible", models.PositiveIntegerField()),
                ("observed_on", models.DateField()),
            ],
            options={
                "indexes": [models.Index(fields=["date"], name="coverage_day_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("date", "axis"), name="coverage_identity")
                ],
            },
        ),
    ]
