# Generated by Django 6.1 on 2026-08-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgvmax", "0003_coverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_on", models.DateField(unique=True)),
                ("rows", models.PositiveIntegerField()),
                ("observed", models.PositiveIntegerField()),
                ("created", models.PositiveIntegerField()),
                ("reappeared", models.PositiveIntegerField()),
                ("vanished", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["observed_on"],
            },
        ),
    ]
