# Generated by Django 6.1 on 2026-08-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgvmax", "0004_ingestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("axis", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("axis", "label"), name="axis_station_identity")
                ],
            },
        ),
    ]
